spring.datasource.url=jdbc:postgresql://localhost:5433/tutoring_db
spring.datasource.username=postgres
spring.datasource.password=0527
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
