spring.datasource.url=jdbc:postgresql://db.xvtzkcopkvhjwfrltwbf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=2uy6r-q+uA9Y22m
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
